name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          input_pr_number: ${{ github.event.pull_request.number }}
          input_data_separator: '\n'
          input_issue_pattern: '\FXDX-\d+\b'

      - name: Print Output - Commit Messages
        id: output-commit-messages
        run: echo "${{ steps.test-action.outputs.commit-messages }}"
      - name: Print Output - Issues
        id: output-issues
        run: echo "${{ steps.test-action.outputs.issues }}"
      - name: Print Output - Files
        id: output-files
        run: echo "${{ steps.test-action.outputs.files }}"

      - name: Print Output - Patch Files Data
        id: output-patch-files-data
        run: echo "${{ steps.test-action.outputs.patch-files-data }}"
      - name: Print Output - Raw Files Data
        id: output-raw-files-data
        run: echo "${{ steps.test-action.outputs.raw-files-data }}"
